spring.application.name=book-service


server.port = 8081


spring.jpa.hibernate.ddl-auto=update

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672


spring.datasource.url= jdbc:postgresql://localhost:5432/SpringBoot
spring.datasource.username=postgres
spring.datasource.password=root

