spring.application.name=03_MAR_DTOLAYERMAPPER

server.port = 2020

spring.datasource.url= jdbc:postgresql://localhost:5432/SpringBoot
spring.datasource.username=postgres
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
